spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/templates
    mode: HTML
    encoding: utf-8
    cache: false
    servlet:
      content-type: text/html
  profiles:
    active: dev
  application:
    name: geewaza-web
    #Jackson 配置
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: ALWAYS
    # 设置时区
    time-zone: GMT+8
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
  servlet:
    #允许最大上传文件大小
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  resources:
    static-locations: classpath:/static/

server:
  port: 8080
# log4j
logging:
  config: classpath:log4j2.xml
  level:
    root: INFO